name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop, feat/advanced-robust-enhancements ]
  pull_request:
    branches: [ main ]

jobs:
  security-check:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Check for sensitive terms
      run: |
        echo "🔍 Running security check..."
        ! grep -R -E "3\.636|0\.262|GSSI|GGSI|GRQIT|coherence|attractor" examples/ || exit 1
        echo "✅ No sensitive terms found"
    
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: security-check
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
        echo "✅ Dependencies installed"
    
    - name: Run linter
      run: npm run lint
    
    - name: Run comment scrubber
      run: npm run prebuild
    
    - name: Run tests
      run: |
        npm test
        echo "✅ All tests passed"
    
    - name: Build production
      run: npm run build
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: production-build
        path: dist/
        retention-days: 7
  
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: production-build
        path: dist/
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist/
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 